import Link from "next/link";
import Navbar from "@/app/_components/layout/Navbar";
import Footer from "@/app/_components/layout/Footer";

export const metadata = {
  title: "Privacy Policy — Duolync",
  description: "Privacy Policy for Duolync. Last updated May 18, 2026.",
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen" style={{ background: "var(--bg-page)" }}>
      <div
        className="fixed top-0 left-0 right-0 z-50"
        style={{
          background: "var(--bg-navbar)",
          backdropFilter: "blur(18px)",
          borderBottom: "1px solid var(--border-card)",
        }}
      >
        <Navbar />
      </div>

      <main className="pt-32 pb-24">
        <div className="container mx-auto px-4 max-w-3xl">
          {/* Header */}
          <div className="mb-12">
            <p className="text-xs font-semibold uppercase tracking-widest text-violet-400 mb-3">
              Legal
            </p>
            <h1
              className="font-display font-bold text-white mb-3"
              style={{ fontSize: "clamp(2rem, 4vw, 3rem)", lineHeight: 1.1 }}
            >
              Privacy Policy
            </h1>
            <p className="text-sm text-zinc-500">Last updated: May 18, 2026</p>
          </div>

          {/* Divider */}
          <div className="h-px mb-12" style={{ background: "var(--border-card)" }} />

          {/* Body */}
          <div className="prose-legal">
            <p>
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
              information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p>
              We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the
              collection and use of information in accordance with this Privacy Policy.
            </p>

            <h2>Interpretation and Definitions</h2>
            <h3>Interpretation</h3>
            <p>
              The words whose initial letters are capitalized have meanings defined under the following conditions. The
              following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>

            <h3>Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul>
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &ldquo;control&rdquo; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
              <li><strong>Company</strong> (referred to as either &ldquo;the Company&rdquo;, &ldquo;We&rdquo;, &ldquo;Us&rdquo; or &ldquo;Our&rdquo; in this Privacy Policy) refers to Duolync.</li>
              <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li><strong>Country</strong> refers to: Georgia</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
              <li><strong>Personal Data</strong> (or &ldquo;Personal Information&rdquo;) is any information that relates to an identified or identifiable individual. We use &ldquo;Personal Data&rdquo; and &ldquo;Personal Information&rdquo; interchangeably unless a law uses a specific term.</li>
              <li><strong>Service</strong> refers to the Website.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
              <li><strong>Website</strong> refers to Duolync, accessible from <a href="https://duolync.com/" target="_blank" rel="noopener noreferrer">https://duolync.com/</a>.</li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>

            <h2>Collecting and Using Your Personal Data</h2>
            <h3>Types of Data Collected</h3>

            <h4>Personal Data</h4>
            <p>
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that
              can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </p>
            <ul>
              <li>Email address</li>
            </ul>

            <h4>Usage Data</h4>
            <p>Usage Data is collected automatically when using the Service.</p>
            <p>
              Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser
              type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time
              spent on those pages, unique device identifiers and other diagnostic data.
            </p>
            <p>
              When You access the Service by or through a mobile device, We may collect certain information automatically,
              including, but not limited to, the type of mobile device You use, Your mobile device&apos;s unique ID, the IP
              address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use,
              unique device identifiers and other diagnostic data.
            </p>
            <p>
              We may also collect information that Your browser sends whenever You visit Our Service or when You access the
              Service by or through a mobile device.
            </p>

            <h4>Tracking Technologies and Cookies</h4>
            <p>
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain
              information. Tracking technologies We use include beacons, tags, and scripts to collect and track information
              and to improve and analyze Our Service. The technologies We use may include:
            </p>
            <ul>
              <li>
                <strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct
                Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept
                Cookies, You may not be able to use some parts of our Service.
              </li>
              <li>
                <strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files
                known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the
                Company, for example, to count users who have visited those pages or opened an email and for other related
                website statistics.
              </li>
            </ul>
            <p>
              Cookies can be &ldquo;Persistent&rdquo; or &ldquo;Session&rdquo; Cookies. Persistent Cookies remain on Your personal computer or
              mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
            </p>
            <p>
              Where required by law, we use non-essential cookies only with Your consent. You can withdraw or change Your
              consent at any time through Your browser/device settings. Withdrawing consent does not affect the lawfulness
              of processing based on consent before its withdrawal.
            </p>
            <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
            <ul>
              <li>
                <strong>Necessary / Essential Cookies</strong> — Type: Session Cookies. These Cookies are essential to provide You
                with services available through the Website and to enable You to use some of its features.
              </li>
              <li>
                <strong>Cookies Policy / Notice Acceptance Cookies</strong> — Type: Persistent Cookies. These Cookies identify if
                users have accepted the use of cookies on the Website.
              </li>
              <li>
                <strong>Functionality Cookies</strong> — Type: Persistent Cookies. These Cookies allow Us to remember choices You
                make when You use the Website, such as remembering your login details or language preference.
              </li>
            </ul>

            <h3>Use of Your Personal Data</h3>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul>
              <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
              <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
              <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
              <li><strong>To contact You</strong> by email, telephone calls, SMS, or other equivalent forms of electronic communication regarding updates or informative communications related to the functionalities, products or contracted services.</li>
              <li><strong>To provide You with news, special offers, and general information</strong> about other goods, services and events which We offer that are similar to those that you have already purchased or inquired about.</li>
              <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
              <li><strong>For business transfers:</strong> We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
              <li><strong>For other purposes</strong> such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service.</li>
            </ul>
            <p>We may share Your Personal Data in the following situations:</p>
            <ul>
              <li><strong>With Service Providers</strong> to monitor and analyze the use of our Service, to contact You.</li>
              <li><strong>For business transfers:</strong> We may share or transfer Your Personal Data in connection with any merger, sale of Company assets, financing, or acquisition.</li>
              <li><strong>With Affiliates:</strong> We may share Your Personal Data with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.</li>
              <li><strong>With business partners</strong> to offer You certain products, services or promotions.</li>
              <li><strong>With other users</strong> when You share Personal Data or otherwise interact in the public areas of the Service.</li>
              <li><strong>With Your consent</strong> for any other purpose.</li>
            </ul>

            <h3>Retention of Your Personal Data</h3>
            <p>
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this
              Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal
              obligations, resolve disputes, and enforce our legal agreements and policies.
            </p>
            <p>We apply different retention periods to different categories of Personal Data:</p>
            <ul>
              <li><strong>Account Information</strong> — retained for the duration of your account relationship plus up to 24 months after account closure.</li>
              <li><strong>Support tickets and correspondence</strong> — up to 24 months from the date of ticket closure.</li>
              <li><strong>Chat transcripts</strong> — up to 24 months for quality assurance and staff training purposes.</li>
              <li><strong>Website analytics data</strong> (cookies, IP addresses, device identifiers) — up to 24 months from the date of collection.</li>
              <li><strong>Server logs</strong> (IP addresses, access times) — up to 24 months for security monitoring and troubleshooting.</li>
            </ul>
            <p>
              We may retain Personal Data beyond the periods stated above where required by legal obligation, to establish or
              defend legal claims, at Your explicit request, or due to technical limitations of backup systems.
            </p>

            <h3>Transfer of Your Personal Data</h3>
            <p>
              Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other
              places where the parties involved in the processing are located. The Company will take all steps reasonably
              necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no
              transfer of Your Personal Data will take place to an organization or a country unless there are adequate
              controls in place.
            </p>

            <h3>Delete Your Personal Data</h3>
            <p>
              You have the right to delete or request that We assist in deleting the Personal Data that We have collected
              about You. You may update, amend, or delete Your information at any time by signing in to Your Account and
              visiting the account settings section, or by contacting Us.
            </p>

            <h2>Disclosure of Your Personal Data</h2>
            <h3>Business Transactions</h3>
            <p>
              If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We
              will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
            </p>
            <h3>Law Enforcement</h3>
            <p>
              Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so
              by law or in response to valid requests by public authorities.
            </p>
            <h3>Other Legal Requirements</h3>
            <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
            <ul>
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
              <li>Protect the personal safety of Users of the Service or the public</li>
              <li>Protect against legal liability</li>
            </ul>

            <h2>Security of Your Personal Data</h2>
            <p>
              The security of Your Personal Data is important to Us, but remember that no method of transmission over the
              Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means
              to protect Your Personal Data, We cannot guarantee its absolute security.
            </p>

            <h2>Children&apos;s Privacy</h2>
            <p>
              Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable
              information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child
              has provided Us with Personal Data, please contact Us.
            </p>

            <h2>Links to Other Websites</h2>
            <p>
              Our Service may contain links to other websites that are not operated by Us. If You click on a third party
              link, You will be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of
              every site You visit. We have no control over and assume no responsibility for the content, privacy policies or
              practices of any third party sites or services.
            </p>

            <h2>Changes to this Privacy Policy</h2>
            <p>
              We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new
              Privacy Policy on this page and updating the &ldquo;Last updated&rdquo; date at the top of this Privacy Policy. You are
              advised to review this Privacy Policy periodically for any changes.
            </p>

            <h2>Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, You can contact us:</p>
            <ul>
              <li>
                By email:{" "}
                <a href="mailto:hello@duolync.com">hello@duolync.com</a>
              </li>
            </ul>
          </div>

          {/* Back link */}
          <div className="mt-16 pt-10" style={{ borderTop: "1px solid var(--border-card)" }}>
            <Link
              href="/"
              className="inline-flex items-center gap-2 text-sm text-zinc-500 hover:text-white transition-colors duration-200"
            >
              ← Back to home
            </Link>
          </div>
        </div>
      </main>

      <Footer />

      <style>{`
        .prose-legal {
          color: #94a3b8;
          font-size: 0.9375rem;
          line-height: 1.8;
        }
        .prose-legal p {
          margin-bottom: 1.25rem;
        }
        .prose-legal h2 {
          font-family: var(--font-display, inherit);
          font-weight: 700;
          font-size: 1.35rem;
          color: #f1f5f9;
          margin-top: 2.75rem;
          margin-bottom: 0.75rem;
        }
        .prose-legal h3 {
          font-weight: 600;
          font-size: 1.05rem;
          color: #cbd5e1;
          margin-top: 2rem;
          margin-bottom: 0.5rem;
        }
        .prose-legal h4 {
          font-weight: 600;
          font-size: 0.9375rem;
          color: #94a3b8;
          margin-top: 1.5rem;
          margin-bottom: 0.4rem;
          text-transform: uppercase;
          letter-spacing: 0.04em;
          font-size: 0.75rem;
        }
        .prose-legal ul {
          list-style: none;
          padding: 0;
          margin-bottom: 1.25rem;
        }
        .prose-legal ul li {
          position: relative;
          padding-left: 1.25rem;
          margin-bottom: 0.6rem;
        }
        .prose-legal ul li::before {
          content: '';
          position: absolute;
          left: 0;
          top: 0.65em;
          width: 5px;
          height: 5px;
          border-radius: 50%;
          background: #6d28d9;
        }
        .prose-legal a {
          color: #a78bfa;
          text-decoration: none;
          transition: color 0.2s;
        }
        .prose-legal a:hover {
          color: #fff;
        }
        .prose-legal strong {
          color: #e2e8f0;
          font-weight: 600;
        }
      `}</style>
    </div>
  );
}
